[build]
  command   = "npm run build"
  functions = "netlify/functions"
  publish   = "public"

# API proxy
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
  force  = true

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200